grafana/phlare

- operations/phlare/helm/phlare/README.md
- operations/phlare/helm/phlare/templates/deployments-statefulsets.yaml
- operations/phlare/helm/phlare/values.yaml
- operations/phlare/jsonnet/values.json
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>
> [Helm] Load environment variables from secrets

- pkg/phlare/phlare.go
Fixes: https://github.com/grafana/phlare/issues/392
> feat: add CLI flag to print version

- .goreleaser.yaml
- Makefile
Fixes https://github.com/grafana/phlare/issues/391
> Fixes goreleaser version in binary

- tools/docker-compose/docker-compose.yml
- tools/docker-compose/java/simple/Dockerfile
- tools/docker-compose/java/simple/build.gradle
- tools/docker-compose/java/springboot/Dockerfile
- tools/docker-compose/java/springboot/build.gradle
- tools/docker-compose/seccomp.json
This also uses seccomp instead of `CAP_SYS_ADMIN` to advertise better security management.
> Upgrades to jpprof 0.1.4

- docs/Makefile
This will avoid breakages by more stricter versions of doc-validator.
> Ensure the doc-validator is using a particular tag

- tools/docker-compose/python/Dockerfile
The python example only works on linux/amd64 or at least linux/arm64 is not supported. Also see https://github.com/timpalpant/mprofile/issues/3.
> Enforce linux/amd64 platform for python

- Makefile
- tools/monitoring/README.md
- tools/monitoring/environments/default/monitoring.libsonnet
- Build correct binary arch and os.
- Remove resource requirement for running locally (otherwise it will lack memory)
- Fixes a typo in the README.md
- Replace datasource with the new Phlare datasource.
> Fixes local kubernetes cluster test

- docs/sources/operators-guide/configure/reference-configuration-parameters/index.md
- pkg/gen/google/v1/profile.pb.go
- pkg/objstore/client/config.go
- pkg/objstore/client/factory.go
- pkg/objstore/providers/cos/bucket_client.go
- pkg/objstore/providers/cos/config.go
- pkg/objstore/providers/cos/config_test.go
Tencent COS service is widely used in China, and currently, Thanos also supports COS as the storage backend of objstore.
So we can support COS as an object storage backend.
> feat(objstore): support Tencent COS object storage

- go.mod
- pkg/phlare/modules.go
- pkg/util/http.go
Since #226 we lost automatic http log and metrics. This PR re-introduce it by fixing the faulty middleware (log).
Fixes https://github.com/grafana/phlare/issues/231
> Fixes http2 instrumentation.

- operations/phlare/helm/phlare/README.md
- operations/phlare/helm/phlare/rendered/micro-services.yaml
- operations/phlare/helm/phlare/rendered/single-binary.yaml
- operations/phlare/helm/phlare/values.yaml
- operations/phlare/jsonnet/values.json
Had to patch this in to conform with our own policies but seems like a good default to have
> Stricter default for `podSecurityContext`

- .github/workflows/test.yml
- operations/phlare/helm/phlare/Chart.yaml
- operations/phlare/helm/phlare/README.md
- operations/phlare/helm/phlare/rendered/micro-services.yaml
- operations/phlare/helm/phlare/rendered/single-binary.yaml
- operations/phlare/helm/phlare/values.yaml
- operations/phlare/jsonnet/values.json
This should be merged after #450.
It releases helm chart v0.1.2 with Phlare version v0.1.1
> Release helm chart v0.1.2 with Phlare version v0.1.1

- pkg/agent/target.go
Since the expected profile output should be gzip:ed.
This way the handler don't have to compress the output, but can instead rely on the webserver, if the implementor wants to.
The golang pprof cli sets this header as well.
> Add gzip accept encoding

- pkg/agent/config.go
- pkg/agent/profiles.go
Fixes https://github.com/grafana/phlare/issues/463
> Fixes the scrape timeout validation.

- pkg/distributor/metrics.go
This was incorrectly using a bitwise xor.
> Fix buckets range for distributor_received_samples.

- pkg/phlaredb/sample_merge.go
In my previous PR I didn't realize but introduce a bug that would only surface when having many mapping.
It would use the id to index the slice to create, where it should just append to the slice.
PS: Tried to create a test but that requires more refactoring so I didn't bother, but happy to try to invest more time.
> Fixes mapping slice insertion

- cmd/profilecli/main.go
- cmd/profilecli/query.go
- go.mod
- go.sum
This adds a query subcommand to download pprof from phlare using profilecli.
This is on top of #474 
Usage:
```
$ profilecli query merge --from now-5m --output pprof=my.pprof
$ profilecli query merge --from now-5m --profile-type memory:alloc_space:bytes:space:bytes
&googlev1.Profile{
SampleType: []*googlev1.ValueType{
&googlev1.ValueType{
Type: 1,
Unit: 2,
},
},
[...]
DropFrames:    0,
KeepFrames:    0,
TimeNanos:     1673453999823000000,
DurationNanos: 300000000000,
PeriodType:    &googlev1.ValueType{
Type:          434,
Unit:          2,
},
Period:            524288,
Comment:           []int64(nil),
DefaultSampleType: 1,
}
```
> Add query subcommand to profilecli for downloading pprof from phlare 

- pkg/phlare/phlare.go
Everything was already in place to expand ENV var to config file except the flag to turn it on.
Fixes #470
> Add missing flags to expand config file

- pkg/phlare/health.go
- pkg/phlare/modules.go
- pkg/phlare/phlare.go
Connect healthcheck service is now correctly checking for services health and only registered on the http port.
Fixes #472
> Correctly implement connect health checker service

- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/publish-technical-documentation-release.yml
The new tokens are managed centrally and have a longer expiry. Administrators of the grafanabot account will be
notified of the pending expiry and the secret can be rotated centrally without the need for a repository administrator to update their secrets.
The existing repository secrets can safely be removed. The tokens for those secrets will be removed by the end of this week.
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
> Update publishing workflows to use organization secret

- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/publish-technical-documentation-release.yml
The new tokens are managed centrally and have a longer expiry. Administrators of the grafanabot account will be
notified of the pending expiry and the secret can be rotated centrally without the need for a repository administrator to update their secrets.
The existing repository secrets can safely be removed. The tokens for those secrets will be removed by the end of this week.
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
(cherry picked from commit 3bdc62b24f0516eca4dc1b9026a5ef5e475af80c)
> [release/v0.1.1] Update publishing workflows to use organization secret (#500)

- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/publish-technical-documentation-release.yml
The new tokens are managed centrally and have a longer expiry. Administrators of the grafanabot account will be
notified of the pending expiry and the secret can be rotated centrally without the need for a repository administrator to update their secrets.
The existing repository secrets can safely be removed. The tokens for those secrets will be removed by the end of this week.
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
(cherry picked from commit 3bdc62b24f0516eca4dc1b9026a5ef5e475af80c)
> [release-v0.1.2] Update publishing workflows to use organization secret (#500)

- pkg/frontend/frontend.go
- pkg/frontend/frontend_scheduler_worker.go
- pkg/phlare/modules.go
- pkg/querier/worker/scheduler_processor.go
- pkg/querier/worker/worker.go
- pkg/scheduler/scheduler.go
This PR ensures the worker and frontend loop will automatically disconnect and reconnect before the handler timeout.
To ensure a query does not time out right after being processed in the querier we also increase the scheduler timeout by 2.
> Improve Worker timeout

- Makefile
- tools/monitoring/environments/default/loki.libsonnet
- tools/monitoring/environments/default/monitoring.libsonnet
- tools/monitoring/environments/default/tempo.libsonnet
- tools/monitoring/jsonnetfile.json
- tools/monitoring/jsonnetfile.lock.json
> Add observability using Loki/Tempo and Grafana Agent

- pkg/phlaredb/deduplicating_slice.go
- pkg/phlaredb/head.go
- pkg/phlaredb/metrics.go
- pkg/phlaredb/phlaredb.go
- pkg/phlaredb/profile_store.go
- Fix block size cutting
- Change thresholds for row group and block target size
> Fix cutting by block size and adjust limits

- pkg/phlare/phlare.go
- pkg/util/http.go
- pkg/util/http_test.go
I guess it's better to use the correct API to give an OK response. We should not use `http.Error` here.
> Use the correct API in readyHandler

- api/gen/proto/go/google/v1/profile.pb.go
- docs/sources/operators-guide/configure/reference-configuration-parameters/index.md
- operations/phlare/helm/phlare/rendered/micro-services.yaml
- operations/phlare/helm/phlare/values-micro-services.yaml
- operations/phlare/jsonnet/values-micro-services.json
Something wrong happens with the last commit :/
> Update helm ingester limits

- pkg/phlaredb/deduplicating_slice.go
`parquet.Writer` is deprcated.
> Use generic writer in deduplicatingSlice

- .golangci.yml
- Makefile
- go.mod
- pkg/agent/agent.go
- pkg/agent/target.go
- pkg/ingester/clientpool/ingester_client_pool.go
- pkg/objstore/objstore.go
- pkg/parquet/group.go
- pkg/phlare/modules.go
- pkg/phlaredb/block_querier.go
- pkg/phlaredb/deduplicating_slice.go
- pkg/phlaredb/functions.go
- pkg/phlaredb/head.go
- pkg/phlaredb/locations.go
- pkg/phlaredb/mappings.go
- pkg/phlaredb/phlaredb.go
- pkg/phlaredb/phlaredb_test.go
- pkg/phlaredb/profile_store.go
- pkg/phlaredb/profiles.go
- pkg/phlaredb/query/predicate_test.go
- pkg/phlaredb/sample_merge.go
- pkg/phlaredb/stacktraces.go
- pkg/phlaredb/strings.go
- pkg/phlaredb/tsdb/index.go
- pkg/phlaredb/tsdb/index/postings.go
- pkg/usagestats/stats.go
- pkg/util/httpgrpc/httpgrpc.go
Update the linter to finally work with Generics. This has surface small interesting issue but also a lot of false negative with `unused` and generics.
But at least now they all run correctly.
> Upgrade linter to work with Go Generics

- cmd/phlare/main.go
- cmd/phlare/main_test.go
- pkg/cfg/files.go
- pkg/phlare/phlare.go
- pkg/phlare/phlare_test.go
- pkg/test/capture.go
- pkg/usage/usage.go
- pkg/util/fieldcategory/overrides.go
close https://github.com/grafana/phlare/issues/367
Try to add `-modules` support. Most code from mimir.
> Add -modules support

- .golangci.yml
- docs/internal/contributing/README.md
- go.mod
- pkg/agent/target.go
- pkg/cfg/cfg_test.go
- pkg/cfg/dynamic_test.go
- pkg/cfg/files.go
- pkg/phlaredb/block/metadata.go
- pkg/phlaredb/phlaredb_test.go
- pkg/phlaredb/shipper/shipper.go
- pkg/phlaredb/tsdb/index/index.go
- pkg/phlaredb/tsdb/index/index_test.go
- pkg/util/error_test.go
1. Bump minimal support version to 1.19
If we use 1.18 to `make lint`, then we will get an error:
```sh
../../go/pkg/mod/honnef.co/go/tools@v0.4.2/unused/unused.go:419:14: obj.Origin undefined (type *types.Var has no field or method Origin)
../../go/pkg/mod/honnef.co/go/tools@v0.4.2/unused/unused.go:421:14: obj.Origin undefined (type *types.Func has no field or method Origin)
note: module requires Go 1.19
../../go/pkg/mod/honnef.co/go/tools@v0.4.2/staticcheck/lint.go:4025:29: righti.Method(i).Origin undefined (type *types.Func has no field or method Origin)
../../go/pkg/mod/honnef.co/go/tools@v0.4.2/staticcheck/lint.go:4030:36: sel.Obj().(*types.Func).Origin undefined (type *types.Func has no field or method Origin)
note: module requires Go 1.19
```
2. Increase the timeout to 10m, because …
> Bump minimal support version to 1.19

- cmd/phlare/main.go
This is a bug in v0.5.0, so we probably need to release v0.5.1 or replace the builds with a fixed on
> Ensure config file parses properly

- Makefile
- cmd/phlare/help-all.txt.tmpl
- cmd/phlare/help.txt.tmpl
- cmd/phlare/main_test.go
- pkg/distributor/distributor_ring.go
- pkg/validation/exporter/ring.go
See https://github.com/grafana/phlare/pull/497#issuecomment-1438260905
> Add help text test

- operations/phlare/jsonnet/phlare-mixin/phlare-mixin/dashboards/phlare-reads.libsonnet
- operations/phlare/jsonnet/phlare-mixin/phlare-mixin/dashboards/phlare-writes.libsonnet
Related to #494 
Make the UID of the `Reads` and `Writes` Mixin Dashboards more unique by appending `phlare-` to them, e.g. `writes` becomes `phlare-writes`, this avoid conflicts with other Mixins (such as the Loki one).
> Mixin: Make the UID of the "Reads" and "Writes" Dashboards more unique

- .github/workflows/test.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Fix deprecated set-output warnings and bump actions/cache to v3

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
> Validates that push request contains at least one sample

- tools/docker-compose/rust/Cargo.lock
- tools/docker-compose/rust/Cargo.toml
- tools/docker-compose/rust/Dockerfile
I tried to run the rust example on my M1 Macbook Pro. When I try to get the profile, it crashed. I think this is an issue from `pprof-rs`.
So I just fix it by using [Platform specific dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies)
See more at: https://github.com/tikv/pprof-rs/issues/131
> Fixed crashed rust example on M1 MacOS

- pkg/pprof/pprof.go
- pkg/pprof/pprof_test.go
We realised that this create a lot of different stacktraces while just the address changes but not the binary itself. 
In the future we'll introduce buildid to recognized binary change, so when a profiles is symbolized we can just get rids on the adresses.
> Remove addresses on symbolized profiles

- tools/docker-compose/golang/main.go
We should use camel case in golang.
> Use camel case instead of snake case in golang example

- pkg/distributor/distributor.go
This is what we use in the overrides file format and will avoid confusion in the future.
> Use IEC size format for rate_limit errors

- cmd/phlare/main.go
Given that identical segments of code are being employed in multiple instances, it is better to utilize the concept of functions, whereby the code is encapsulated within a named block that can be invoked at various points within the program.
> refactor: cmd/phlare/main.go

- pkg/phlaredb/block_querier_test.go
- pkg/phlaredb/deduplicating_slice.go
- pkg/phlaredb/head.go
- pkg/phlaredb/metrics.go
- pkg/phlaredb/metrics_test.go
- pkg/phlaredb/profile_store.go
- pkg/phlaredb/profile_store_test.go
- pkg/phlaredb/profiles.go
- pkg/phlaredb/querier_test.go
- pkg/phlaredb/query/metrics.go
- pkg/util/prometheus.go
Not only this is easier to manage, but this is also more resilient.
> Refactor metrics in PhlareDB

- .github/workflows/weekly-release.yml
Those releases power the Grafana Labs internal roll-outs, that occur
weekly into our production systems.
Goreleaser is used to build those releases with the same config that is
used for the project releases.
To get around some limitations around semver in goreleaser we have to
imitate a version with local git tags.
> Use goreleaser to build weekly releases

- README.md
When one clicks the channel link Slack asks for an email to log into the Grafana Slack workspace. That email needs to be invited to the workspace first. It is not obvious how to do that. Add a link to slack.grafana.com which can be used to get the invitation.
> Add instructions on how to join the Grafana Slack workspace

- .goreleaser.yaml
A change that I made for the weekly releases using goreleases #576  was display the unixtime instead.
> Use date instead of timestamp

- pkg/api/index.gohtml
- pkg/api/memberlist_status.gohtml
Add a home page link for the Phlare logo. This would help us go back to the home page.
Also, it is quite common on other websites.
> Add the home page link for Phlare logo

- pkg/agent/profiles.go
- pkg/agent/profiles_test.go
Refer to Prometheus and Pyroscope, support dynamic setting of timeout and interval based on service discovery info.
> feat(agent): support interval and timeout label for agent scrape

- pkg/phlaredb/profile_store.go
- pkg/phlaredb/profile_store_test.go
This adds a flush benchmark and an optimization to reduce memory usage.
```
❯ benchstat before.txt after.txt                      
name      old time/op    new time/op    delta
Flush-16     400ms ± 8%     249ms ±10%  -37.76%  (p=0.008 n=5+5)
name      old alloc/op   new alloc/op   delta
Flush-16    1.03GB ± 0%    0.20GB ± 1%  -80.12%  (p=0.008 n=5+5)
name      old allocs/op  new allocs/op  delta
Flush-16     8.26k ± 1%     3.43k ± 1%  -58.54%  (p=0.008 n=5+5)
```
> Improve profiles flushing using ReadRowsFrom

- pkg/phlaredb/delta.go
- pkg/phlaredb/delta_test.go
- pkg/phlaredb/head.go
- pkg/phlaredb/head_test.go
- pkg/phlaredb/profile_store.go
- pkg/phlaredb/profiles.go
This fixes the computation of delta profiles. We were assuming that only one sample per stacktraces is passed to the delta function.
However this wasn't true, after ingesting symbols we can endup with the same stacktraces in different samples.
This PR makes sure that before computing the samples we sanitize the input.
I've also included couple of fixes to avoid retaining the memory here and there and combine with correct delta this has drastically improve performance of ingester.
This is the result in a busy cluster.
> Fixes delta of samples computation

- pkg/querier/querier.go
This will stop doing 500 when entering a wrong query. This is because it was propagated to ingester and the response was wrapped into a multierror with httpgrpc code.
I went for the easy route and pre-validate.
> Validates label matchers in the querier

- cmd/phlare/Dockerfile
- cmd/phlare/debug.Dockerfile
- tools/docker-compose/golang/Dockerfile
- tools/upgrade-alpine-version.sh
- Update alpine version to 3.17.3: Addresses some CVE in openssl (not likely affected by this ourselves)
- Add upgrade alpine version script
> Update alpine version to 3.17.3

- cmd/phlare/help-all.txt.tmpl
- cmd/phlare/help.txt.tmpl
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/limiter.go
- pkg/ingester/limiter_test.go
- pkg/testhelper/ring.go
- pkg/validation/limits.go
This adds shuffle sharding for the write path. 
It will allow to configure the amount of shards of the whole ingester set that will be available to particular tenants.
> Adopt ingester shuffle sharding from mimir

- pkg/phlaredb/profile_store_test.go
- pkg/phlaredb/profiles.go
- pkg/pprof/pprof.go
Remove TODO and use the binary search here.
> Use binary search in `getSeriesIndex`

- pkg/distributor/distributor.go
- pkg/ingester/ingester.go
- pkg/pprof/pprof.go
In some cases an object allocated from the pool is not returned back to the pool. The change is aimed at improving ownership of the objects allocated in pools at pprof parsing specifically, which affects both distributor and ingester services
> Improve memory ownership at pprof parsing

- .gitignore
- Makefile
This makes sure that every `make deploy` rolls out even though when there was not git commit. This is achieved by tagging the docker image has in the pods annotations.
> Annotate `make deploy` rollouts with image id

- pkg/phlare/modules.go
- pkg/querier/grpc_handler.go
- pkg/querier/grpc_roundtripper.go
- pkg/querier/http.go
- pkg/util/connectgrpc/connectgrpc.go
This will allow better query handling in micro-services mode.
As part of that I implemented wrapping of connect in HTTPGRPC by using the generated clients and handlers. (Avoids the static code that was required before).
> Also register pyroscope query handlers at query-frontend

- package.json
- public/app/app.tsx
- public/app/components/LoadAppNames.tsx
- public/app/overrides/components/ExportData.tsx
- public/app/overrides/components/TimelineChart/TimelineChartWrapper.tsx
- public/app/pages/ComparisonView.tsx
- public/app/pages/SingleView.tsx
- public/app/redux/store.ts
- scripts/webpack/webpack.dev.js
Not fully useful since there's no timelines yet.
Also the only way to access it right now is to visit the page directly. Will add a sidebar after all the pages are done.
> feat: comparison page

- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/index.go
- pkg/api/index_test.go
- pkg/phlare/modules.go
- pkg/phlare/phlare.go
- pkg/util/gziphandler/doc.go
- pkg/util/gziphandler/gzip.go
- pkg/util/gziphandler/gzip_go18.go
- pkg/util/gziphandler/gzip_go18_test.go
- pkg/util/gziphandler/gzip_test.go
close https://github.com/grafana/phlare/issues/587
close https://github.com/grafana/phlare/pull/637
Adapt the gzip support from Mimir as well.
> Refactor all APIs to a better structure

- Makefile
[This issue](https://github.com/golangci/golangci-lint/issues/2649) has already been solved. So I think it is ready to use when formatting.
> Upgrade golangci-lint and enable it when formatting

- pkg/api/api.go
- public/app/app.tsx
- public/assets.go
- public/assets_embedded.go
- scripts/webpack/webpack.common.js
- scripts/webpack/webpack.dev.js
- scripts/webpack/webpack.prod.js
Fixes https://github.com/grafana/phlare/issues/642
Keep in mind https://github.com/grafana/phlare/issues/638 is still outstanding, but will definitely build upon the work here.
Backend doesn't do anything.
Basepath is `/` since it's served under `http://localhost:4040`
Backend serves `/ui/assets` requests (css/js) using the embed file server.
All other routes are served the `index.html`, which then are handled via the frontend router (`react-router`).
When building for production, a `BASEPATH` env var is dynamically set in webpack to `/ui`. This is so that React Router knows that it needs to take that into account. This part will likely change when https://github.com/grafana/phlare/issues/638 is addressed.
> fix: serve UI in prod mode

- docs/sources/operators-guide/configure/configuring-memberlist.md
- pkg/frontend/frontend.go
- pkg/frontend/frontend_scheduler_worker.go
- pkg/frontend/frontend_test.go
- pkg/querier/worker/scheduler_processor.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/scheduler/schedulerdiscovery/ring.go
- pkg/util/logger.go
This is misleading and really hard to fix later, this will also require to modify some of the existing dashboards.
In my opinion, we should also rename all metrics to use the `pyroscope_` prefix
> Remove `cortex_` prefix from scheduler/frontend metrics

- pkg/querier/querier.go
I don't fully understand this part, but it seems the value is never null, but a 0 value, hence making the check wrong and breaking tree truncation (https://github.com/grafana/phlare/pull/634) and generating a panic [here](https://github.com/grafana/phlare/blob/ae47e35de8af0e959d04c3430cd1e87f75766ae6/pkg/querier/flamegraph.go#L181).
> fix: max nodes check

- pkg/phlaredb/profile_store_test.go
- pkg/phlaredb/profiles.go
- pkg/pprof/pprof.go
This are additional test cases from the PR #621, which we reverted as a hotfix.
> Add test cases for getSeriesRef

- pkg/api/api.go
Follow up https://github.com/grafana/phlare/pull/645
Test locally:
- Before change
- After change
> Make both `/ui/?query=` and `/ui?query=` work

- operations/phlare/jsonnet/phlare-mixin/phlare-mixin/dashboards/dashboard-utils.libsonnet
- operations/phlare/jsonnet/phlare-mixin/phlare-mixin/dashboards/phlare-reads.libsonnet
- operations/phlare/jsonnet/phlare-mixin/phlare-mixin/dashboards/phlare-writes.libsonnet
- operations/phlare/jsonnet/phlare-mixin/phlare-mixin/recording_rules.libsonnet
- pkg/distributor/distributor.go
- pkg/distributor/metrics.go
- pkg/frontend/frontend.go
- pkg/frontend/frontend_scheduler_worker.go
- pkg/frontend/frontend_test.go
- pkg/ingester/ingester.go
- pkg/phlare/modules.go
- pkg/phlaredb/head_test.go
- pkg/phlaredb/metrics.go
- pkg/phlaredb/metrics_test.go
- pkg/phlaredb/phlaredb.go
- pkg/phlaredb/query/metrics.go
- pkg/phlaredb/shipper/shipper.go
- pkg/querier/querier.go
- pkg/querier/worker/scheduler_processor.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/scheduler/schedulerdiscovery/ring.go
- pkg/usagestats/reporter.go
- pkg/util/recovery.go
- pkg/validation/exporter/exporter.go
- pkg/validation/exporter/exporter_test.go
- pkg/validation/exporter/ring.go
- pkg/validation/validate.go
This is a breaking change for all dashboards and rules.
In some future we plan to rename the project from Phlare to Pyroscope, so we rather take this hit early.
> Update all metrics to be prefixed with pyroscope rather than phlare

- .github/workflows/test.yml
format step takes ~7 minutes and tests take ~7 minutes, running them serially is quite slow
For reference:
Before:
After:
> ci: run 'make fmt check' concurrently

- pkg/querier/querier.go
It was reported that querier panics on `LabelNames` request. A sample stack trace:
```
2023-05-08T15:11:38Z	fatal error: concurrent map writes
2023-05-08T15:11:38Z	
2023-05-08T15:11:38Z	goroutine 8627 [running]:
2023-05-08T15:11:38Z	github.com/bufbuild/connect-go.(*connectClient).WriteRequestHeader(0xc0002b6980, 0x0, 0x479b09?)
2023-05-08T15:11:38Z		github.com/bufbuild/connect-go@v1.4.1/protocol_connect.go:248 +0x1b8
2023-05-08T15:11:38Z	github.com/bufbuild/connect-go.NewClient[...].func2(0xc000ccd3b0)
2023-05-08T15:11:38Z		github.com/bufbuild/connect-go@v1.4.1/client.go:102 +0x12c
2023-05-08T15:11:38Z	github.com/bufbuild/connect-go.(*Client[...]).CallUnary(0x2bb5a12?, {0x4a7e820?, 0xc0005ba900?}, 0x40a7cd?)
2023-05-08T15:11:38Z		github.com/bufbuild/connect-go@v1.4.1/client.go:121 +0x50 …
```
> Fix concurrent use of LabelValuesRequest and LabelNamesRequest

- pkg/distributor/metrics.go
This was omitted in https://github.com/grafana/phlare/pull/623
> Correctly register replication factor metric

- pkg/ingester/ingester.go
- pkg/ingester/query.go
- pkg/ingester/retention.go
- pkg/phlaredb/block_querier.go
- pkg/phlaredb/deduplicating_slice.go
- pkg/phlaredb/head.go
- pkg/phlaredb/head_queriers.go
- pkg/phlaredb/phlaredb.go
- pkg/phlaredb/phlaredb_test.go
- pkg/phlaredb/profile_store.go
- pkg/phlaredb/profile_store_test.go
Resolves https://github.com/grafana/phlare/issues/687
> Fix queries and storage block operations synchronisation

- package.json
- yarn.lock
Mostly performance upgrades from here https://github.com/grafana/pyroscope/pull/1957
> chore: get latest pyroscope-oss code

- public/app/overrides/models/app.ts
- public/app/overrides/services/apps.spec.ts
- public/app/overrides/services/apps.ts
Apparently it's possible to have labelSets that don't have neither `pyroscope_app` nor `service_name`
> fix: filter out labelsset without the required labels instead of crashing

- cypress/e2e/smoke.cy.ts
- public/app/app.tsx
- public/app/redux/store.ts
- public/app/util/history.ts
Closes https://github.com/grafana/phlare/issues/722
Funnily enough I couldn't reproduce in CI, but trust me ~bro~, the issue is indeed happening.
But basically for `redux-query-sync` to work, the same `history` instance needs to be shared across the app. Didn't dive too deep, but it was affecting how other components that use the `useLocation` were rendered. Basically `Sidebar` wouldn't rerender when the route changes, therefore its navigation items wouldn't include the query parameter!
> fix: routing

- .github/workflows/e2e.yaml
- pkg/frontend/frontend.go
Closes https://github.com/grafana/phlare/issues/727
It waits on `/ready` instead of hitting `/ui`. There's still a chance that we try to run tests while the query-frontend is being initialized, but it's already a better heuristic than simply hitting the /ui.
> ci: [e2e] wait for /ready instead of hitting the ui directly

- go.mod
- go.sum
- go.work.sum
Here badgerdb  was downgraded from v2.2007.4 to  v2.2007.2
https://github.com/grafana/phlare/commit/82621087d0a2b24abd8ab20dff15de9d24b23eb6#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L266
and v2.2007.3 includes the fix for building on 32bit architectures 
https://github.com/dgraph-io/badger/pull/1558
Fixes
https://github.com/grafana/phlare/issues/744
> fix: build on 32bit

- docs/sources/configure-client/_index.md
Updates links to point at grafana.com instead of pyroscope.io
> docs: Update links to point at grafana.com instead of pyroscope.io

- pkg/phlaredb/profiles.go
The PR causes profile store to release profile objects when a new row group is flushed on disk. Currently, objects remain in memory and are not eligible for garbage collection.
Memory consumption of the ingester service has a rather interesting pattern:
Heap In-use (as reported by pprof):
In-use objects:
Where a half of the capacity is taken by `convertSamples`
Notice that once a new head is created, memory consumption goes to zero and then grows to ~50% of the max within the next 15-20 minutes. Supposedly, the trend indicates how samples are accumulated. However, I find it interesting that there's another "half": main contributors here are the stacktraces in-memory slice and in-memory parquet readers (that is not supposed to occupy so much memory as it only reads locations, strings, …
> Free profile objects when cutting a row group

- pkg/ingester/pyroscope/ingest_adapter.go
This is a second attempt to fix `500` in `/pyroscope/ingest` https://github.com/grafana/phlare/issues/714
- if the request is bad and we can't convert to pprof - return `connect.CodeInvalidArgument` which will become `400`
- if the app has no profile type suffix - assume it is "cpu" and not treat as error
> fix: /pyroscope/ingest return 400 in case of bad request

- cmd/phlare/help-all.txt.tmpl
- cmd/phlare/help.txt.tmpl
- pkg/phlare/phlare.go
enables block + mutex profiling, sets it to 5 by default, allows for changes via config
> chore: enables mutex and block profiling for pyroscope itself

- pkg/phlaredb/profile_store.go
Introduced by https://github.com/grafana/phlare/commit/faf62ed434feef64d4db61797b3f92659b4b55e2 this was because before we were not flushing async and we would only sort/add profiles one at a time.
> Fix concurrent map access in ingester

- docs/sources/configure-client/_index.md
- docs/sources/configure-client/language-sdks/dotnet.md
- docs/sources/configure-client/language-sdks/ebpf.md
- docs/sources/configure-client/language-sdks/go_push.md
- docs/sources/configure-client/language-sdks/java.md
- docs/sources/configure-client/language-sdks/nodejs.md
- docs/sources/configure-client/language-sdks/python.md
- docs/sources/configure-client/language-sdks/ruby.md
Updates docs for how to send data to phlare or grafana cloud and removes some reference to og-pyroscope cloud
also fixes small ui thing:
> docs: Update docs for cloud

- docs/sources/configure-client/_index.md
Corrects the Link to the Grafana Agent Examples, previously was pointing to `php` examples, now points to Grafana Agent examples.
> [Docs] - Correct Link to Grafana Agent Examples

- .github/workflows/release.yml
- .github/workflows/weekly-release.yml
On average, the release process takes a little over half an hour (see https://github.com/grafana/phlare/actions/workflows/weekly-release.yml), and the default goreleaser timeout is 30m.
I think it makes sense to increase goreleaser timeout to 60m. Long term we should try to decrease the job duration.
> Increase goreleaser timeout

- docs/sources/configure-server/reference-configuration-parameters/index.md
- operations/phlare/helm/phlare/rendered/micro-services.yaml
- operations/phlare/helm/phlare/rendered/single-binary.yaml
- operations/phlare/helm/phlare/templates/deployments-statefulsets.yaml
This will reduce the number of members to join at startup. Before it would try to join all members, now using `dns+` it will only select a subset.
See https://github.com/grafana/loki/pull/9723
> Reduce join_members for memberlist using dns+

- pkg/phlaredb/block_querier.go
- pkg/phlaredb/block_querier_test.go
- pkg/phlaredb/metrics.go
- pkg/phlaredb/profile_store.go
This add the number of block currently opened and also the total samples in memory.
> Add block opened metrics

- cmd/profilecli/canary_exporter.go
- cmd/profilecli/client.go
- cmd/profilecli/main.go
- pkg/pprof/testhelper/profile_builder.go
This adds an exporter to `profilecli`, which can test the happy path of a Phlare cluster and export its findings through metrics.
It currently tests:
- `ingest:` Ability to ingest a profile
- `query-instant`: Ability to query this just ingested profile
> Adds canary exporter to `profilecli`

- pkg/parquet/row_reader.go
- pkg/parquet/row_reader_test.go
- pkg/parquet/row_writer.go
- pkg/parquet/row_writer_test.go
- pkg/phlaredb/profile_store.go
- pkg/phlaredb/profile_store_test.go
- pkg/phlaredb/schemas/v1/profiles.go
- pkg/phlaredb/schemas/v1/profiles_test.go
Fixes https://github.com/grafana/phlare/issues/800
This k-way merge rowgroups on disk when we flush to a full block. Which means now a single series is expected to appear in only on rowgroup.
The only caveat if we only cut the final file rowgroup per rowcount but I think we can live with this since we never cut by size.
> Sort Profiles across row groups when flushing blocks

- pkg/querier/replication.go
DoUntilQuorum has changed in behaviour and by default cancels all context even succesful one.
We should use `DoUntilQuorumWithoutSuccessfulContextCancellation` instead which makes it obvious we don't want cancellation for successful ones.
> Use DoUntilQuorumWithoutSuccessfulContextCancellation instead of DoUntilQuorum

- ebpf/symtab/procmap.go
- ebpf/symtab/stat_placeholder.go
- make Stat placeholder exported - same as in linux & darwin
- copy unix.mkdev function to be used on windows
> fix(ebpf): compilation on windows and freebsd

- Makefile
- Correct environment variables GOOS GOOARCH: Was not setup correctly
- Give empty second argument: Avoids a warning
> Fix makefile issues

- Makefile
This allows better testing for blocks on ingester local and bucket storage
> Reduce max duration for kind deploys

- pkg/iter/profiles.go
- pkg/parquet/row_reader.go
- pkg/querier/select_merge.go
- pkg/util/loser/tree.go
- pkg/util/loser/tree_test.go
This makes loser.Tree aware of Err() and stops as soon as an iterator return false from Next() with an Err() != nil.
Supersedes https://github.com/grafana/phlare/pull/828
> Adds iteration error support in the loser.Tree

- public/app/components/AppSelector/AppSelector.module.css
- public/app/components/AppSelector/AppSelector.tsx
Adds search to app selector bar... 
Warning -- this was a [chatgpt generated change](https://chat.openai.com/share/aff13004-9e18-4630-aeac-13c3f3290a35) but seems to be looking / working fine or at least better than having no search at all. 
https://github.com/grafana/phlare/assets/23323466/44338f49-904f-46ad-89b1-0d5e8cd77e95
> Add app selector search

- operations/phlare/helm/phlare/Chart.yaml
- operations/phlare/helm/phlare/README.md
- operations/phlare/helm/phlare/rendered/micro-services.yaml
- operations/phlare/helm/phlare/rendered/single-binary.yaml
- operations/phlare/helm/phlare/templates/deployments-statefulsets.yaml
- operations/phlare/helm/phlare/values-micro-services.yaml
- operations/phlare/jsonnet/values-micro-services.json
It's been reported multiple times that the unfinished block is lost at shutdown. One of the most common reasons in case of k8s deployment is the fact that ingesters may not be able to flush all the data before being terminated forcibly due to expiration of `terminationGracePeriodSeconds` (defaults to 30s).
The change makes the parameter configurable: now it is set to 10m by default for ingesters when deployed as micro services.
Related #688
> Add terminationGracePeriodSeconds helm value

- pkg/iter/tree.go
- pkg/parquet/row_reader.go
- pkg/parquet/row_reader_test.go
- pkg/parquet/row_writer.go
- pkg/parquet/row_writer_test.go
This is a refactoring a bit how we deal with RowReader but also fixes a bug where we were re-used the `At` of the inner iterator inside the RowReader.
Currently causing no grief but did when working on compaction. Already include https://github.com/grafana/phlare/pull/842.
Closes https://github.com/grafana/phlare/pull/842
> Fixes iterator At value re-used

- ebpf/symtab/procmaps_test.go
Use same packed dev structure in tests as in implementation
We use mkdev result as a cache key, it does not matter what the implementation is, it just should be the same
> fix(ebpf): procmap parse test fix

- pkg/phlaredb/block_querier.go
- pkg/phlaredb/block_querier_test.go
- pkg/phlaredb/head.go
- pkg/phlaredb/sample_merge.go
- pkg/phlaredb/schemas/v1/schema_test.go
- pkg/phlaredb/schemas/v1/strings.go
The change makes in-memory parquet reader to not use the stored schema for reconstruction via `reflect`, and use hand-written reconstruction instead.
> Optimise in-memory parquet reader

- public/app/overrides/components/Toolbar.tsx
I have no idea what I am doing, but this should fix the linting issue we see on every PR.
> Fix linting error in frontend

- pkg/phlaredb/query/iters.go
- pkg/phlaredb/query/iters_test.go
- Implement BinaryJoinIterator.Seek() properly
- Fix nextOrSeek entry conditions
> Fix BinaryJoinIterator.Seek

- public/app/components/AppSelector/AppSelector.module.css
- public/app/components/AppSelector/AppSelector.tsx
This takes the:
- [app selector from grafana/pyroscope](https://github.com/grafana/pyroscope/blob/ce966012e5ada7d4d27d7f07a6261ff11433d955/webapp/javascript/components/AppSelector/index.tsx)
- [app selector from grafana/phlare](https://github.com/grafana/phlare/blob/64da02ed79fdaa09b75ed34f45e63b18665fc42d/public/app/components/AppSelector/AppSelector.tsx) (which overrides the grafana/pyroscope version to accomodate the different datastructure that exists in phlare, but not pyroscope
And then I asked for some help from [chatgpt](https://chat.openai.com/share/289269ce-43a8-48f8-a597-8a2117c531d9) to bring some functionality from the pyroscope version into the phlare version.
Had to make some tweaks after, but now it looks better. Would like to merge this and get it into the next weekly …
> Fix app selector scrolling

- cmd/profilecli/query.go
my brain is unable to remember `time.RFC3339` format :)
> chore(profilecli): accept timestamps for queries
