- .github/workflows/test.yml
- Makefile
No longer neccessary as Phlare is no longer private.
> Remove ssh-agent and authetnication for go modules

- examples/README.md
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
> fix error link in doc

- docs/sources/operators-guide/architecture/block-format/_index.md
- docs/sources/operators-guide/configure-agent/language-support/jvm.md
> Fix some markdown errors in docs.

- Makefile
- tools/kubernetes/java-simple-deployment.yaml
This adds a kubernetes example for java deployment.
Works with the `CAP_PERFMON`
> Adds a kubernetes example for java

- docs/sources/_index.md
- docs/sources/operators-guide/configure-agent/about-the-agent.md
- docs/sources/operators-guide/configure-agent/grafana-agent.md
- docs/sources/operators-guide/deploy-kubernetes/_index.md
- docs/sources/operators-guide/get-started/_index.md
- docs/sources/release-notes/v0.1/index.md
Linter is happy but hard to validate those works.
@jdbaldry what do you think ?
> Fixes latest docs validation link to grafana.com

- pkg/phlaredb/block_querier.go
Previously if one of the tables open would fail, the block would be considered open and leading to panic.
> Ensure opening block is atomic

- go.mod
- go.sum
- pkg/phlare/modules.go
This enabled fgprof which allowed me to verify that we can correctly parse those profiles.
> Adds fgprof to Phlare

- Makefile
- operations/phlare/helm/phlare/Chart.yaml
- operations/phlare/helm/phlare/README.md
- operations/phlare/helm/phlare/rendered/micro-services.yaml
- operations/phlare/helm/phlare/rendered/single-binary.yaml
Was forgotten in https://github.com/grafana/phlare/pull/393. This will release a new version.
> Raise helm chart version

- .github/workflows/test.yml
This will reenable the deploys to dev-001
> Update name of github token

- tools/docker-compose/docker-compose.yml
- tools/docker-compose/golang/Dockerfile
- tools/docker-compose/golang/go.mod
- tools/docker-compose/golang/main.go
- tools/docker-compose/phlare.yaml
This PR adds a golang example.
> feat(examples): add golang example

- .github/workflows/test.yml
> Fix token reference in test workflow

- Makefile
- operations/phlare/jsonnet/phlare-mixin/phlare-mixin/dashboards/phlare-reads.libsonnet
Update the read dashboard with the up-to-date set of APIs.
> Updates the read dashboard

- docs/sources/operators-guide/configure-agent/language-support/python.md
> Add docs for Django support

- docs/sources/operators-guide/configure/reference-configuration-parameters/index.md
- docs/sources/operators-guide/configure/reference-configuration-parameters/index.template
- pkg/agent/config.go
- pkg/gen/google/v1/profile.pb.go
Add agent config to support HTTP service discovery, use Prometheus HTTP SD config.
> feat(agent/sd): add support HTTP service discovery

- .github/workflows/test.yml
- Makefile
> Removes the CI for building the Grafana image.

- docs/sources/operators-guide/get-started/_index.md
This fixes the download URL and adds unpacking.
> Fix download instructions for Phlare

- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/publish-technical-documentation-release.yml
(cherry picked from commit 9c283be9cf26ee816cdb6f3812882d1e74580574)
> [release/v0.1.1] Update publishing workflows to use PATs with fine-grained access control

- .github/workflows/helm-release.yaml
- operations/phlare/helm/cr.yaml
Please see: https://github.com/grafana/helm-charts/pull/2107
> Remove helm chart signing

- .github/workflows/release.yml
- .goreleaser.yaml
- Makefile
- docs/internal/RELEASE.md
This will automatically create the release and all artefacts once a tag is pushed.
A draft release is also created. see example https://github.com/grafana/phlare/releases/tag/untagged-96f9b9bc7a91de2423a7
> Add a github action to release automatically when tagging the repo.

- pkg/usagestats/reporter.go
Remove duplicate if statement.
> Usage stats reporter: fix to remove duplicate if block

- Makefile
Let me know what you think, but this makes the test output way more readable in CI.
> Use gotestsum

- tools/docker-compose/java/simple/build.gradle
- tools/docker-compose/java/simple/gradle/wrapper/gradle-wrapper.properties
- tools/docker-compose/java/springboot/build.gradle
- Update jpprof to 0.1.6
- Fix gradle problem with snapshot
> Update docker-compose java examples

- pkg/phlaredb/block_querier.go
- pkg/phlaredb/head.go
- pkg/phlaredb/head_queriers.go
- pkg/phlaredb/profile_store.go
- pkg/phlaredb/profile_test.go
- pkg/phlaredb/profiles.go
- pkg/phlaredb/query/iters.go
- Fix adding new profiling series after row group segment has been cut.
- Close row Group file, before it gets reopened
> Fix regressions on the new ingress flush to disk handling.

- operations/phlare/helm/phlare/Chart.yaml
- operations/phlare/helm/phlare/README.md
- operations/phlare/helm/phlare/rendered/micro-services.yaml
- operations/phlare/helm/phlare/rendered/single-binary.yaml
- operations/phlare/helm/phlare/values.yaml
- operations/phlare/jsonnet/values.json
Move main to the latest release changes.
> Update helm doc for v0.4.0

- go.mod
- go.sum
- go.work.sum
We will need a new release for this one.
> Update prometheus to have latest relabeling support

- Makefile
> Move from kubeval to kubeconform

- .github/workflows/test.yml
Some actions are using checkout@v2 and some are using checkout@v3. Just bump all checkout@v2 to checkout@v3.
> Bump checkout@v2 to checkout@v3

- pkg/distributor/distributor.go
> Remove global metrics and stats

- pkg/api/index.go
- pkg/phlare/modules.go
Follow up https://github.com/grafana/phlare/pull/547#issuecomment-1451458156
Add index pages for status service
> Add index pages for status service

- pkg/api/index.go
- pkg/api/memberlist_status.go
- pkg/api/memberlist_status.gohtml
- pkg/phlare/modules.go
close https://github.com/grafana/phlare/issues/56
It looks like:
> Add `memberlist` API support

- pkg/distributor/distributor_test.go
- pkg/distributor/metrics.go
- remove useless convert
- use some consts to make bucket range test more maintainable
> Make bucket range test more maintainable

- pkg/phlare/modules.go
- pkg/util/http.go
- pkg/util/http_test.go
Still needs to implement https://demo.pyroscope.io/api/apps
> Bring back the Pyroscope API

- cmd/profilecli/query.go
This will configure the related `X-Scope-OrgID`.
Note: basic auth is already supported by using the `http://user:password@host` notation.
> Allow specifying a tenant ID in profilecli

- pkg/phlaredb/delta.go
https://github.com/grafana/phlare/pull/596#discussion_r1151055486
> fix: allow __delta__ label to force-enable as well as force-disable delta computation

- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/weekly-release.yml
- .goreleaser.yaml
- tools/upgrade-go-version.sh
- Update golang version to 1.19.8
- Add script to update go versions
> Update golang version to 1.19.8

- pkg/querier/http.go
This uses the og-pyroscope library for parsing timestamps.
> Fix from/until parsing in pyroscope/render call

- package.json
- public/app/overrides/components/AppSelector/Label.tsx
- scripts/webpack/webpack.common.js
- tsconfig.json
- yarn.lock
Honestly not sure about using "Proflie ID", any thoughts @Rperry2174?
Edit: used "Profile Type" as suggested
> chore: replace 'Application' for 'ProfileID' to better match phlare's semantics

- pkg/phlaredb/profile_store_test.go
- pkg/phlaredb/profiles.go
- pkg/pprof/pprof.go
> Revert "Use binary search in `getSeriesIndex`"

- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/weekly-release.yml
- .goreleaser.yaml
> Update golang version to 1.19.9

- pkg/phlare/modules.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
Done the TODO. I think it is safe to move it into the new function.
> Make clients options non global

- pkg/phlare/phlare.go
Currently the health check under `/ready` will only show the count of services in a particular state, this will make sure we will display the state and the services names.
After a recent deploy I saw a couple of replicas unavailable, be the ready endpoint did not really reveal which service was failing this adapts the output to more specific.
Before
```
Some services are not Running:
Running: 9
Starting: 2
```
After 
```
Some services are not Running:
Running: [agent distributor ingester memberlist-kv overrides-exporter query-scheduler ring server usage-stats]
Starting: [querier query-frontend]
```
> When ready check fails display service names

- pkg/api/api.go
- pkg/util/http.go
- pkg/util/interceptor.go
close https://github.com/grafana/phlare/issues/641
Print all parameters of the Querier request.
> Add log request middleware for Querier

- Makefile
Introduced by https://github.com/grafana/phlare/commit/982a19fd98a21911c35bc87a1500c6ec2b0947e7
> Fixes the make generate target

- pkg/ingester/pyroscope/ingest_adapter.go
- pkg/phlaredb/deduplicating_slice.go
close https://github.com/grafana/phlare/issues/733
If the service_name is present, utilize it and maintain appname as a label.
> Allow the service_name label to exist 

- docs/sources/configure-server/reference-configuration-parameters/index.md
- go.work.sum
- pkg/storegateway/gateway.go
This was a mistake from me, the config should be inline to avoid having the property `config` below `store_gateway`
> Inline correctly the store-gateway config

- docs/sources/configure-client/grafana-agent.md
Adding grafana agent docs related https://github.com/grafana/pyroscope/pull/1958
> Add grafana agent docs

- pkg/storegateway/blocks.gohtml
- pkg/storegateway/gateway_blocks_http.go
> Add block stats to store-gateway status page

- pkg/ingester/query_test.go
Add tests for `LabelValues` and `ProfileTypes`.
> Enable metadata test for ingester

- public/README.md
- Refine the md format
- Add links to some repos and files
- I guess the last `grafana/pyroscope` should be `grafana/phlare`.
> Add links to frontend README

- docs/sources/configure-client/language-sdks/nodejs.md
Updates node docs as a result of some unclear language that caused issues with some users getting started here. Also made node more consistent with the other docs for other languages
> docs: Update node docs

- pkg/model/labels.go
- pkg/phlaredb/block_querier.go
- pkg/phlaredb/head.go
- pkg/phlaredb/head_queriers.go
- pkg/phlaredb/head_test.go
- pkg/phlaredb/profiles.go
- pkg/phlaredb/sample_merge.go
- pkg/phlaredb/schemas/v1/profiles.go
This determines the partition of a particular profile, by looking first
at its metadata:
* If there is a `Filename` on the main mapping use its
filepath.Base(Filename)
* Failing that take the externally supplied `service_name`
* Fallback to `unknown`
Take the underlying string value and hash.
> Introduce stacktrace partition

- docs/sources/configure-client/language-sdks/_index.md
Updates old pyroscope links -- yes I missed this and this is a reason that we should duplicate this stuff in docs, but I think its worth it for discoverability of where people are trying to go
> docs: Updates old pyroscope links

- go.mod
- go.sum
See https://github.com/dgryski/go-groupvarint/pull/4 for details
Thanks @simonswine!
> Update go-groupvarint dependency

- go.mod
- go.sum
[fix(pprof): bug reusing slices #1939 ](https://github.com/grafana/pyroscope/pull/1939)
> fix: update og pyroscope to include pprof parsing panic fix

- tools/docker-compose/rust/Cargo.lock
- tools/docker-compose/rust/Cargo.toml
- tools/docker-compose/rust/Dockerfile
- tools/docker-compose/rust/src/main.rs
Notice some warnings in the dependencies
> Update rust dependencies

- go.mod
- go.sum
https://github.com/grafana/pyroscope/pull/1986
> chore(pyroscope ingest): update oss for pyspy pprof formatting

- Makefile
- cmd/phlare/debug.Dockerfile
Also upgrades dlv version to the latest v1.21.0.
> Fix dlv for cross compiling
